### ISSUE TITLE
Make campaign texts optional

### ISSUE THREAD

**Issue by CooperSmout** [FreeOurKnowledge/platform#8]
Seeking development help to move this project into the next phase.

We're currently developing ideas for a [new range of campaigns](https://github.com/FreeOurKnowledge/discussion/issues), based on feedback about our 3 flagship campaigns ([Green, Gold and Platinum Open Access](https://www.freeourknowledge.org/#campaigns)). These new campaigns will target simple actions (e.g., submit a [Registered Report](https://github.com/FreeOurKnowledge/discussion/issues/8)) across a wide range of open science behaviours (including but not limited to publishing) and use small thresholds to increase our chances of success (e.g., 100 pledges). Our plan is to bring a few small-scale campaigns to threshold, demonstrate the crowdacting concept in action, and then build on that momentum to host ever-larger and more broad-reaching campaigns in the future. 

But in order to post these new campaigns, we need to make minor changes to the platform code so that it can host the new campaigns. Specifically, if you click pledge on a [campaign page](https://www.freeourknowledge.org/campaign/create-your-own-campaign), it takes you to a [pledge page](https://www.freeourknowledge.org/pledge/create-your-own-campaign) that shows 3 text boxes with adjustable parameters prior to signing the pledge. We need to make the appearance of the first two of these boxes optional ("I pledge to uphold the above Criteria..." and "This pledge will apply to research outputs..."), so that they can be removed for the new campaigns. In the Content Management System, these texts are called 'Dynamic texts' and labelled 'pledge1' and 'pledge2'.

I'm anticipating this work will only take a few hours for an experienced coder, and allow us to move forward with a wide range of new campaigns. Please get in touch or post below if you can help or have any questions.

**Comment by CooperSmout** [comment]
@ZoranPandovski I just created a separate Issue (#14) for the structural change to the pledging workflow we talked about on the phone earlier (simplifying the process to a single button + page). Like I said, not critical, but could reduce barriers to entry if it's not too hard a change to make.

**Comment by ZoranPandovski** [comment]
Ok, perfect. I guess it wouldn't take to much effort to do that.
